### ISSUE TITLE
stuck at building an image 

### ISSUE THREAD

**Issue by FBIanderson** [darwin-containers/rund#38]
After i configed the containerd/dockerd/rund, i run 
```
docker run --rm -it ghcr.io/macoscontainers/macos-jail/ventura:latest echo "Hello from macOS container ^_^"
```
it is ok , 
when i run 
```
sudo docker build . -t bla
```
it stucked  after " => => transferring dockerfile: 151B"
here is the Dockerfile 
```
FROM ghcr.io/macoscontainers/macos-jail/ventura:latest
RUN echo "hello world"
```

**Comment by slonopotamus** [comment]
Hi. Please, make sure you're using latest versions of components. I am not reproducing `operation not permitted: unknown` with containerd 0.0.2 + dockerd 0.0.7 + rund 0.0.7.

**Comment by bickkysahani** [comment]
I have latest versions of these.
containerd 0.0.2 + dockerd 0.0.7 + rund 0.0.7.

when I try to build a local project, it stucks on RUN pip install -r requirements.txt.


<img width="1242" alt="Screenshot 2024-01-28 at 11 50 46" src="https://github.com/macOScontainers/rund/assets/49335486/bcc546f8-9192-46f4-98f6-2f55361d6c2b">

here's my Dockerfile
```
# Pull base image
FROM python:3.8.17-slim-bullseye

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /react-django-auth/backend/

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY . .
```

here's the docker compose
```
version: "3.9"

services:
  web:
    build: .
    tty: true
    command: python /react-django-auth/backend/manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: web2
    volumes:
      - .:/react-django-auth/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - v-network

  db:
    image: postgis/postgis:11-2.5-alpine
    container_name: db2
    restart: always
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - v-network
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  v-network:
    external: false

```
